// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jusefajumidquszwpzgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1c2VmYWp1bWlkcXVzendwemduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTkwNDQsImV4cCI6MjA3MTA5NTA0NH0.ZFFbnGziU9H4Rl6kZTGpHlHfRIoV98-PqxLqSDoTs6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});